project:
  type: book
  output-dir: docs

book:
  title: "Closing Time"
  repo-url: "https://github.com/gvwilson/closure"
  repo-actions: [edit, source, issue]
  chapters:
    - index.qmd
    - intro/index.qmd
    - gas/index.qmd
    - handover/index.qmd
    - deliberate/index.qmd
    - disaster/index.qmd
    - abrupt/index.qmd
    - care/index.qmd
    - finale/index.qmd
  appendices:
    - license/index.qmd
    - conduct/index.qmd
    - contributing/index.qmd
    - bibliography/index.qmd
    - glossary/index.qmd
    - fire/index.qmd
    - nesbitt/index.qmd

bibliography: bibliography/references.bib
csl: _extras/book.csl

filters:
  - _bin/links.lua

shortcodes:
  - _bin/glossary.lua
  - _bin/inc-noh1.lua

format:
  html:
    css: assets/mccole.css
    link-citations: true
    theme: cosmo
    toc: true
